### PR TITLE
Show languages for given flags

### PR DESCRIPTION
**Pull request by addon-rajada**
Show language instead country code at label.
It doesn't affect the sort by language feature.

### CODE REVIEW

**Comment by addon-rajada** [comment]
Also:
- fix KeyError when "languages" not in result object
- keeps resolution order when language sorting by using a counter

**Comment by Sam-Max** [comment]
thanks for your PR, the countries list a big one that is loading in memory all at once, and that is not good for performance, maybe there is another way to get country name based on flag unicode.

**Comment by addon-rajada** [comment]
How about keep just `name, alpha2, language, flag and unicode` entries for each country?
It would reduce file size from 266 KB to few kilobytes

**Comment by Sam-Max** [comment]
> How about keep just `name, alpha2, language, flag and unicode` entries for each country? It would reduce file size from 266 KB to few kilobytes

Ok

**Comment by addon-rajada** [comment]
Last commits:
- lowered file size to 36kb
- binary search for faster language matching
- avoid duplicate language
- updated branch

**Pull request merged**
